### PR TITLE
Create john_snow_labs

### PR DESCRIPTION
**Pull request by jobarratt**

### CODE REVIEW

**Comment by jobarratt** [comment]
@amercader we need a way to share this with David before we publish. Can we do this?

**Comment by amercader** [comment]
@jobarratt Is this rendered view enough?

https://github.com/frictionlessdata/frictionlessdata.io/blob/7589d8ec6a38e9fca5ab09ee2457aecd1eb69e50/_case_studies/john_snow_labs.md

**Comment by jobarratt** [comment]
Yep @amercader  :) um do you know how i screwed up the footnotes?

**Comment by amercader** [comment]
@jobarratt it's fine, it's Jekyll syntax that the GitHub parser does not understand (see other [files](https://github.com/frictionlessdata/frictionlessdata.io/blob/master/_case_studies/tesera.md))

**Comment by jobarratt** [comment]
@amercader ok that should be all good now. Can you check and merge the pull request? Can you check i added the logo correctly.

**Comment by amercader** [comment]
@jobarratt FYI, file names should contain hyphens `-`, not undescores, and the logo image needs to be actually uploaded to `/img/case-studies/`. I did these changes myself.

Also the page is not linked from the case-studies index page.

**Pull request merged**
