### PR TITLE
improve python guide

### PR DESCRIPTION
**Pull request by roll**
@danfowler 
Does this tutorial works?
https://github.com/frictionlessdata/datapackage-py/issues/75

### CODE REVIEW

**Comment by roll** [comment]
It works.. but it's only because `resources` have also `url` field. So safer to pass `url` to `push_datapackage`.

**Comment by rufuspollock** [comment]
@roll should we still merge this - not sure I understand the change.

**Comment by roll** [comment]
Current version works only if resource have a full url path:
- http://data.okfn.org/data/core/s-and-p-500/datapackage.json - works because `resources[].url` has been added here
- https://raw.githubusercontent.com/datasets/s-and-p-500/master/datapackage.json - doesn't work because no `resources[].url`

So much safer to pass `url` to `push_datapackage` = better to merge this PR.

**Comment by danfowler** [comment]
Yup, this is better, thanks! 👍

**Pull request merged**
